# Generated by Django 6.1.1 on 2026-09-26 17:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.IntegerField(default=0, verbose_name='Tồn thực tế')),
                ('reserved', models.IntegerField(default=0, verbose_name='Đã giữ cho đơn bán')),
                ('avg_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Giá vốn bình quân')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='catalog.product', verbose_name='Sản phẩm')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='catalog.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Tồn kho',
                'ordering': ['warehouse__code', 'product__sku'],
                'constraints': [models.UniqueConstraint(fields=('product', 'warehouse'), name='uniq_stock_product_warehouse'), models.CheckConstraint(condition=models.Q(('on_hand__gte', 0)), name='stock_on_hand_gte_0'), models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='stock_reserved_gte_0'), models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('on_hand'))), name='stock_reserved_lte_on_hand')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Nhập kho'), ('OUT', 'Xuất kho'), ('ADJUST', 'Điều chỉnh'), ('TRANSFER_IN', 'Chuyển kho đến'), ('TRANSFER_OUT', 'Chuyển kho đi')], max_length=20, verbose_name='Loại')),
                ('quantity', models.IntegerField(verbose_name='Số lượng (+/-)')),
                ('balance_after', models.IntegerField(verbose_name='Tồn sau giao dịch')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Đơn giá')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Chứng từ')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Thời điểm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày ghi sổ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.product', verbose_name='Sản phẩm')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Phiếu xuất nhập',
                'verbose_name_plural': 'Lịch sử xuất nhập',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['product', 'warehouse', 'occurred_at'], name='inventory_s_product_46406b_idx')],
            },
        ),
    ]
