# Generated by Django 6.1.1 on 2026-09-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklevel',
            options={'ordering': ['warehouse__code', 'product__sku'], 'permissions': [('adjust_stocklevel', 'Có thể điều chỉnh tồn kho / chuyển kho')], 'verbose_name': 'Tồn kho', 'verbose_name_plural': 'Tồn kho'},
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='reorder_point',
            field=models.PositiveIntegerField(default=0, help_text='Do lệnh run_forecast tính; 0 = dùng ROP của sản phẩm.', verbose_name='ROP tại kho'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='safety_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Tồn an toàn tại kho'),
        ),
    ]
