# Generated by Django 6.1.1 on 2026-09-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stocklevel_options_stocklevel_reorder_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklevel',
            name='reorder_point',
            field=models.PositiveIntegerField(blank=True, help_text='Do lệnh run_forecast tính; để trống = dùng ROP của sản phẩm.', null=True, verbose_name='ROP tại kho'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='safety_stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tồn an toàn tại kho'),
        ),
    ]
