# Generated by Django 6.1.1 on 2026-09-26 18:02

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('period_start', models.DateField(verbose_name='Từ ngày')),
                ('period_end', models.DateField(verbose_name='Đến ngày')),
                ('kpi_json', models.JSONField(blank=True, default=dict, verbose_name='KPI')),
                ('body', wagtail.fields.StreamField([('kpi_summary', 0), ('heading', 1), ('paragraph', 2), ('bullets', 4)], blank=True, block_lookup={0: ('reports.models.KPISummaryBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Tiêu đề'}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Đoạn văn'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Ý'}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Danh sách'})}, verbose_name='Nội dung')),
                ('generated_by_ai', models.BooleanField(default=False, verbose_name='Do AI viết')),
                ('ai_warnings', models.JSONField(blank=True, default=list, verbose_name='Cảnh báo kiểm tra số liệu')),
            ],
            options={
                'verbose_name': 'Báo cáo AI',
                'verbose_name_plural': 'Báo cáo AI',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ReportIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Giới thiệu')),
            ],
            options={
                'verbose_name': 'Danh sách báo cáo',
            },
            bases=('wagtailcore.page',),
        ),
    ]
