# Generated by Django 6.1.1 on 2026-09-26 17:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('code', models.CharField(blank=True, editable=False, max_length=30, unique=True, verbose_name='Số PO')),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('APPROVED', 'Đã duyệt'), ('PARTIAL', 'Nhận một phần'), ('RECEIVED', 'Đã nhận đủ'), ('CANCELLED', 'Đã hủy')], default='DRAFT', editable=False, max_length=20, verbose_name='Trạng thái')),
                ('source', models.CharField(choices=[('MANUAL', 'Thủ công'), ('AI', 'Đề xuất AI'), ('INVOICE_OCR', 'Đọc hóa đơn')], default='MANUAL', editable=False, max_length=20, verbose_name='Nguồn tạo')),
                ('order_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày đặt')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Ngày dự kiến nhận')),
                ('received_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Ngày nhận đủ')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=16, verbose_name='Tổng tiền')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Ngày duyệt')),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='catalog.supplier', verbose_name='Nhà cung cấp')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='catalog.warehouse', verbose_name='Kho nhận')),
            ],
            options={
                'verbose_name': 'Đơn mua hàng',
                'verbose_name_plural': 'Đơn mua hàng (PO)',
                'ordering': ['-order_date', '-code'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('received_quantity', models.PositiveIntegerField(default=0, editable=False, verbose_name='Đã nhận')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Đơn giá')),
                ('order', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='catalog.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Dòng PO',
                'verbose_name_plural': 'Dòng PO',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
