# Generated by Django 6.1.1 on 2026-09-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-order_date', '-code'], 'permissions': [('approve_purchaseorder', 'Có thể duyệt / hủy đơn mua hàng'), ('receive_purchaseorder', 'Có thể nhận hàng theo đơn mua')], 'verbose_name': 'Đơn mua hàng', 'verbose_name_plural': 'Đơn mua hàng (PO)'},
        ),
    ]
