# Generated by Django 6.1.1 on 2026-09-26 17:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã KH')),
                ('name', models.CharField(max_length=200, verbose_name='Tên khách hàng')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Điện thoại')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('tax_code', models.CharField(blank=True, max_length=20, verbose_name='Mã số thuế')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang giao dịch')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã NCC')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhà cung cấp')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Người liên hệ')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Điện thoại')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('tax_code', models.CharField(blank=True, max_length=20, verbose_name='Mã số thuế')),
                ('lead_time_days', models.PositiveIntegerField(default=7, verbose_name='Thời gian giao hàng (ngày)')),
                ('rating', models.PositiveSmallIntegerField(default=3, help_text='1 (kém) đến 5 (rất tốt)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hợp tác')),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục sản phẩm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('sku', models.CharField(max_length=30, unique=True, verbose_name='Mã SKU')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('unit', models.CharField(choices=[('cai', 'Cái'), ('hop', 'Hộp'), ('goi', 'Gói'), ('chai', 'Chai'), ('lon', 'Lon'), ('thung', 'Thùng'), ('kg', 'Kg'), ('bo', 'Bộ')], default='cai', max_length=10, verbose_name='Đơn vị tính')),
                ('cost_price', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Giá nhập')),
                ('sale_price', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Giá bán')),
                ('reorder_point', models.PositiveIntegerField(default=0, help_text='Khi tồn khả dụng + đang về ≤ ROP thì cần đặt hàng. Tuần 2 sẽ tính tự động.', verbose_name='Điểm đặt hàng lại (ROP)')),
                ('safety_stock', models.PositiveIntegerField(default=0, verbose_name='Tồn kho an toàn')),
                ('lead_time_days', models.PositiveIntegerField(blank=True, help_text='Để trống để dùng lead time của NCC mặc định.', null=True, verbose_name='Lead time (ngày)')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kinh doanh')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Danh mục')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hình ảnh')),
                ('default_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.supplier', verbose_name='NCC mặc định')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã kho')),
                ('name', models.CharField(max_length=100, verbose_name='Tên kho')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Thủ kho')),
            ],
            options={
                'verbose_name': 'Kho',
                'verbose_name_plural': 'Kho hàng',
                'ordering': ['code'],
            },
        ),
    ]
