# Generated by Django 6.1.1 on 2026-09-26 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('purchasing', '0002_alter_purchaseorder_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(db_index=True, verbose_name='Ngày chạy')),
                ('method', models.CharField(default='level+seasonal', max_length=50, verbose_name='Phương pháp')),
                ('window_days', models.PositiveIntegerField(verbose_name='Số ngày lịch sử')),
                ('avg_daily', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='TB/ngày (cả kỳ)')),
                ('recent_daily', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='TB/ngày (28 ngày)')),
                ('std_daily', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Độ lệch chuẩn/ngày')),
                ('seasonal_factor', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Hệ số mùa vụ')),
                ('forecast_daily', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Dự báo/ngày')),
                ('lead_time_days', models.PositiveIntegerField(verbose_name='Lead time')),
                ('safety_stock', models.PositiveIntegerField(verbose_name='Tồn an toàn')),
                ('reorder_point', models.PositiveIntegerField(verbose_name='ROP')),
                ('order_up_to', models.PositiveIntegerField(verbose_name='Mức tồn tối đa (S)')),
                ('available', models.IntegerField(verbose_name='Tồn khả dụng')),
                ('on_order', models.IntegerField(verbose_name='Đang về')),
                ('stockout_days', models.PositiveIntegerField(default=0, verbose_name='Số ngày hết hàng')),
                ('weekly_sales', models.JSONField(default=list, verbose_name='Doanh số 12 tuần')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='catalog.product', verbose_name='Sản phẩm')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='catalog.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Dự báo nhu cầu',
                'verbose_name_plural': 'Dự báo nhu cầu',
                'ordering': ['-run_date', 'warehouse__code', 'product__sku'],
            },
        ),
        migrations.CreateModel(
            name='ReorderSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('available', models.IntegerField(verbose_name='Tồn khả dụng')),
                ('on_order', models.IntegerField(verbose_name='Đang về')),
                ('reorder_point', models.PositiveIntegerField(verbose_name='ROP')),
                ('suggested_qty', models.PositiveIntegerField(verbose_name='SL hệ thống đề xuất')),
                ('ai_action', models.CharField(blank=True, choices=[('', 'Chưa có AI'), ('order', 'Nên đặt'), ('wait', 'Chờ thêm'), ('review', 'Cần xem lại')], max_length=10, verbose_name='AI khuyến nghị')),
                ('ai_adjusted_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='SL AI đề xuất')),
                ('ai_confidence', models.CharField(blank=True, max_length=10, verbose_name='Độ tin cậy')),
                ('ai_reason', models.TextField(blank=True, verbose_name='Lý do')),
                ('ai_flagged', models.BooleanField(default=False, verbose_name='Bị guardrail chặn')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã tạo PO'), ('REJECTED', 'Từ chối'), ('EXPIRED', 'Hết hiệu lực')], db_index=True, default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('final_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='SL duyệt')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='forecast.demandforecast')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_suggestions', to='catalog.product', verbose_name='Sản phẩm')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='purchasing.purchaseorder', verbose_name='PO')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reorder_suggestions', to='catalog.supplier', verbose_name='Nhà cung cấp')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_suggestions', to='catalog.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Đề xuất nhập hàng',
                'verbose_name_plural': 'Đề xuất nhập hàng',
                'ordering': ['warehouse__code', 'product__sku'],
            },
        ),
        migrations.AddConstraint(
            model_name='demandforecast',
            constraint=models.UniqueConstraint(fields=('run_date', 'product', 'warehouse'), name='uniq_forecast_run'),
        ),
    ]
