# Generated by Django 6.1.1 on 2026-09-26 18:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Bật tính năng AI')),
                ('model', models.CharField(blank=True, help_text='Để trống để dùng biến môi trường OPENAI_MODEL.', max_length=100, verbose_name='Model OpenAI')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.2'), help_text='Để trống nếu model không hỗ trợ tham số temperature.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Temperature')),
                ('enable_reorder', models.BooleanField(default=True, verbose_name='AI giải thích đề xuất nhập hàng')),
                ('enable_report', models.BooleanField(default=True, verbose_name='AI viết báo cáo')),
                ('enable_assistant', models.BooleanField(default=True, verbose_name='Trợ lý hỏi đáp dữ liệu')),
                ('max_adjust_pct', models.PositiveIntegerField(default=30, help_text='AI chỉ được đổi số lượng đề xuất trong biên này; vượt quá thì giữ số của hệ thống và gắn cờ.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Biên điều chỉnh tối đa của AI (%)')),
                ('service_level', models.DecimalField(decimal_places=3, default=Decimal('0.950'), help_text='0.95 = 95% chu kỳ không hết hàng (z ≈ 1.65).', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('0.999'))], verbose_name='Mức phục vụ mục tiêu')),
                ('review_period_days', models.PositiveIntegerField(default=7, verbose_name='Chu kỳ xem xét đặt hàng (ngày)')),
                ('forecast_window_days', models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(28)], verbose_name='Số ngày lịch sử dùng để dự báo')),
            ],
            options={
                'verbose_name': 'Cấu hình AI & dự báo',
            },
        ),
        migrations.CreateModel(
            name='AICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('reorder', 'Đề xuất nhập hàng'), ('product', 'Phân tích sản phẩm'), ('report', 'Báo cáo'), ('assistant', 'Trợ lý hỏi đáp')], max_length=20, verbose_name='Tính năng')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('success', models.BooleanField(default=True, verbose_name='Thành công')),
                ('error', models.TextField(blank=True, verbose_name='Lỗi')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='Token vào')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='Token ra')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='Thời gian (ms)')),
                ('request_excerpt', models.TextField(blank=True, verbose_name='Trích yêu cầu')),
                ('response_excerpt', models.TextField(blank=True, verbose_name='Trích phản hồi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời điểm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Nhật ký gọi AI',
                'verbose_name_plural': 'Nhật ký gọi AI',
                'ordering': ['-created_at'],
                'permissions': [('use_assistant', 'Có thể dùng trợ lý AI'), ('generate_report', 'Có thể tạo báo cáo AI'), ('run_forecast', 'Có thể chạy dự báo nhập hàng')],
            },
        ),
    ]
