# Generated by Django 6.1.1 on 2026-09-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='enable_invoice',
            field=models.BooleanField(default=True, verbose_name='Đọc hóa đơn NCC từ ảnh'),
        ),
        migrations.AlterField(
            model_name='aicalllog',
            name='feature',
            field=models.CharField(choices=[('reorder', 'Đề xuất nhập hàng'), ('product', 'Phân tích sản phẩm'), ('report', 'Báo cáo'), ('assistant', 'Trợ lý hỏi đáp'), ('invoice', 'Đọc hóa đơn')], max_length=20, verbose_name='Tính năng'),
        ),
    ]
