# Generated by Django 6.1.1 on 2026-09-26 17:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('code', models.CharField(blank=True, editable=False, max_length=30, unique=True, verbose_name='Số SO')),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('CONFIRMED', 'Đã xác nhận'), ('SHIPPED', 'Đã giao'), ('CANCELLED', 'Đã hủy')], default='DRAFT', editable=False, max_length=20, verbose_name='Trạng thái')),
                ('order_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày đặt')),
                ('confirmed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Ngày xác nhận')),
                ('shipped_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Ngày giao')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=16, verbose_name='Tổng tiền')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='catalog.customer', verbose_name='Khách hàng')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='catalog.warehouse', verbose_name='Kho xuất')),
            ],
            options={
                'verbose_name': 'Đơn bán hàng',
                'verbose_name_plural': 'Đơn bán hàng (SO)',
                'ordering': ['-order_date', '-code'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=0, help_text='Để trống để lấy giá bán của sản phẩm.', max_digits=14, verbose_name='Đơn giá')),
                ('order', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_lines', to='catalog.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Dòng SO',
                'verbose_name_plural': 'Dòng SO',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
