# Generated by Django 6.1.1 on 2026-09-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-order_date', '-code'], 'permissions': [('confirm_salesorder', 'Có thể xác nhận / hủy đơn bán hàng'), ('ship_salesorder', 'Có thể xuất kho giao đơn bán hàng')], 'verbose_name': 'Đơn bán hàng', 'verbose_name_plural': 'Đơn bán hàng (SO)'},
        ),
    ]
