# Generated by Django 6.1.1 on 2026-09-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='shipped_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Ngày giao'),
        ),
    ]
